### ISSUE TITLE
AssertEqualsTable only fails if columns exist in both tables and values differ

### ISSUE THREAD

**Issue by vzdm** [tSQLt-org/tSQLt#100]
I expected a failure when using AssertEqualsTable and the columns do not match on the expected and actual tables. 
In my example I use temp tables but this has no impact on the result where the fail is expected

The documentation is absent on the desired behavior in this scenario. 

    CREATE SCHEMA [test_table]
    GO
    EXECUTE sp_addextendedproperty @name = N'tSQLt.TestClass', @value = 1, @level0type = N'SCHEMA', @level0name = N'test_table';
    GO
    CREATE OR ALTER PROCEDURE test_table.test_expect_fail_but_succeeds 
    AS
    BEGIN

    DECLARE @a INT = 1
           ,@b INT = 2;

    CREATE TABLE #expected (
        a INT NOT NULL
    );

    INSERT INTO #expected(
        a
    )
    VALUES(
        @a
    )

    CREATE TABLE #actual (
        a INT NULL
       ,b INT NULL
    );

    INSERT INTO #actual(
        a
       ,b
    )
    VALUES(
        @a
       ,@b
    );

    EXEC tsqlt.AssertEqualsTable @Expected = N'#expected'
                                ,@Actual = N'#actual';

    END
    GO
    EXEC tsqlt.run 'test_table.test_expect_fail_but_succeeds';

    GO

    --Use below instead.
    CREATE OR ALTER PROCEDURE test_table.test_expect_fail_and_does_fail 
    AS
    BEGIN

    DECLARE @a INT = 1
           ,@b INT = 2;

    CREATE TABLE test_table.expected (
        a INT NOT NULL
    );

    INSERT INTO test_table.expected(
        a
    )
    VALUES(
        @a
    )

    CREATE TABLE test_table.actual (
        a INT NULL
       ,b INT NULL
    );

    INSERT INTO test_table.actual(
        a
       ,b
    )
    VALUES(
        @a
       ,@b
    );

    EXEC tsqlt.AssertEqualsTable @Expected = N'test_table.expected'
                                ,@Actual = N'test_table.actual'
                                ,@Message = N'AssertEqualsTable FAIL';

    EXEC tsqlt.AssertEqualsTableSchema @Expected = N'test_table.expected'
                                      ,@Actual = N'test_table.actual'
                                      ,@Message = N'AssertEqualsTableSchema FAIL';

    END
    GO
    EXEC tsqlt.run 'test_table.test_expect_fail_and_does_fail';
    GO

**Comment by vzdm** [comment]
Most likely this is as expected but the document could be a bit clearer on this point where the number of columns in the expected/actual differ

**Comment by NogaWeb** [comment]
Good to know, thanks 😊
