### ISSUE TITLE
PowerShell Module

### ISSUE THREAD

**Issue by lowlydba** [tSQLt-org/tSQLt#101]
As a big fan of tSQLt, I've used it extensively in projects but often find myself using Pester to orchestrate the overall testing. As a result, I think a PowerShell wrapped module would be really helpful for:

* Downloading & installing
* Running tests
* Setting up classes
* Returning results as objects 
* Working more easily with Pester
* etc.

With no timeline in mind, I've got a few barebones pieces started locally. I wanted to see if there was interest in adding it officially to the tSQLt-org account, otherwise I'm happy to brand it as the 'unofficial' module and work off my own account. Any other thoughts, requests, or comments on this are welcome!

One adjacent question for the maintainer: do you plan on updating the github versions to match the ones available on the website? Or should the two versions listed on tsqlt.org be considered the only two viable options for people to use?

**Comment by mbt1** [comment]
Would love to hear more about this. How are you using Pester for tSQLt currently? What is missing in that solution? How is what you're proposing going to fit in and make that easier?

**Comment by LowlyDBA** [comment]
Here's a sample [Appveyor build](https://ci.appveyor.com/project/LowlyDBA/dba-multitool/builds/40273392/job/9fmv2qaa35mfpw04) from where I use it the most. 

Currently I have one-off scripts to handle the downloading and installation, but standardizing that would be useful and one less unrelated piece to worry about in a T-SQL based project. In Pester, I use DbaTools to execute [ad hoc queries](https://github.com/LowlyDBA/dba-multitool/blob/master/tests/sp_estindex.Tests.ps1) to run the tests, which is *okay*, but again would be simpler if I had a wrapper function instead.

I haven't experimented with the xml output from tSQLt much, but presumably there are also some benefits to being able to return that as a PS object and/or integrate with external test tools more generically. Right now I just use the text output for manually reading on Appveyor if I get a fail. Having the object returned would make it easier to write retry logic (still missing from Pester currently) for individual tests, for example. 

Most of the grunt work probably would still be left to doing in T-SQL with tsqlt directly, but for CI I think the above commands could really help simplify the overall build process so you only need to focus on having your test scripts in a given directory.

**Comment by lizbaron** [comment]
> One adjacent question for the maintainer: do you plan on updating the github versions to match the ones available on the website? Or should the two versions listed on tsqlt.org be considered the only two viable options for people to use?

Just to quickly answer this question --> Yes. The tsqlt.org website hosts the only official and stable versions. The github versions will always be "ahead" because of ongoing development.

But can you say more about why you are asking? Is there anything specific that you are looking for?

**Comment by qkub** [comment]
Assuming i understand what @LowlyDBA  is after i would like to share my 50 cents to this debate. There's a feature in https://tsqlt.org/820/tsqlt-v1-0-7942-19440-release-notes/ where one could use DACPAC style of deployment and using dr. John's PublishDacPac i'm deploying tSQLt to raw database in CI scenarios for TEST execution. It goes something like this: 
Publish-DacPac -DacPacPath "D:\tSQLt\tSQLt_Current\tSQLtDacpacs\tSQLt.2019.dacpac" -DacPublishProfile "d:\tSQLt\TSQLt.publish.xml" -Server $sqlTestInstance -Database $sqlTgtDB

Now there are subsequent deploys of TEST suite DACPACs in our build and this further binds the idea into a tSQLt CI scenario. 
I'm not entirely done with this prototype of CI build and i'm really eager to se how DACPAC part of release package is going to drive it's future. I enjoy this setup so far as it seems rather clean in definition but let's see/hope if it provides a durable and reliable foundation.

**Comment by lowlydba** [comment]
At this point I'm moving away from Appveyor in favor of Github's CI environment due to the native support and vast amount of Github Actions to reduce CI scripts. 

I'll probably be making a tsqlt Github Action as a result and intend to put it in the marketplace if time allows.

**Comment by lowlydba** [comment]
https://github.com/lowlydba/tsqlt-installer is the new github action for anyone interested.
