### ISSUE TITLE
Typo prevents from publishing to Case sensitive server

### ISSUE THREAD

**Issue by andreassundstrom** [tSQLt-org/tSQLt#155]
In the procedure `tSQLt.Private_NoTransactionHandleTable` there is a typo preventing us from publishing tSQLt to case sensitive server. Should be `@cmd`.
https://github.com/tSQLt-org/tSQLt/blob/c63e2d268a136154fad3648bc41cf4fd32bd2106/Source/tSQLt.Private_NoTransactionHandleTable.ssp.sql#L25
Variable declaration:
````SQL
  DECLARE @cmd NVARCHAR(MAX);
````
I can submit PR for fix if you want, but I'm not very faimiliar with the project.

**Comment by mbt1** [comment]
Marking this as a bug. We'll work on getting a case-sensitive server into the build pipeline. (To clarify, all build databases are already case sensitive. That SQL Server shows different behavior when the server collation is case sensitive I was not aware of.)

**Comment by lizbaron** [comment]
Fixed and tested. Merged to main. Will publish shortly.

**Comment by andreassundstrom** [comment]
@lizbaron Will this be available from the tSQLt website, or do you scheduele releases?

**Comment by mbt1** [comment]
The release (V1.0.8083.3529) is now available on tSQLt.org. Please go to the [download page](https://tsqlt.org/download/tsqlt/) to get it.

**Comment by andreassundstrom** [comment]
Wow amazing, awesome work. This will really help our company implementing sql server unit testing in our Swedish health care environment. Thank you so much for quick response!
