### ISSUE TITLE
Redundancy in the last example of the tutorial

### ISSUE THREAD

**Issue by shepard8** [tSQLt-org/tSQLt#164]
In the tutorial (https://tsqlt.org/user-guide/tsqlt-tutorial/)

The last example ends with:

```
IF (@errorThrown = 0 OR (EXISTS (SELECT 1 FROM FinancialApp.Sales)))
BEGIN
    EXEC tSQLt.Fail 'Sales table should not allow invalid currency';
END;

IF EXISTS (SELECT 1 FROM FinancialApp.Sales)
    EXEC tSQLt.Fail 'Sales table should not allow invalid currency';
```

The two last lines are unnecessary since this is tested already just above. This is a small issue but the tutorial should show how easy it is to use the tool, which is why I believe these useless lines are bad :smile: 

Regards,

**Comment by JerryNixon** [comment]
I've removed this section. You are correct. The update will show in the new docs.

**Comment by JerryNixon** [comment]
https://github.com/tSQLt-org/tSQLt/pull/171

**Comment by 3milio** [comment]
Just FYI, this is still showing up in the link originally provided.
