### ISSUE TITLE
PrepareServer.sql missing in version=1-0-5873-27393

### ISSUE THREAD

**Issue by pilif42** [tSQLt-org/tSQLt#197]
I go to https://tsqlt.org/download/tsqlt/?version=1-0-5873-27393.
I download tSQLt_V1.0.5873.27393.zip
It does not contain PrepareServer.sql

**Comment by mbt1** [comment]
That version is from before the time when PrepareServer was included. On Azure SQL databases you should not need it. You might have to enable CLR.  

On 2005, if you're still on that version, you need to enable CLR and potentially set the database to trustworthy.
