### ISSUE TITLE
tsqlt.class.sql $$SCHEMA_NAME$$ convention conflicts with DbUp

### ISSUE THREAD

**Issue by provenstyle** [tSQLt-org/tSQLt#2]
We use DbUp to handle our data base schema migrations and I am also using it to deploy my tSQLt tests to different environments.  The $$Variable$$ convention used below is conflicting with DbUps variable convention of $Variable$.  Could it be changed to something different here?  This is the only place I saw it in the code.

Maybe ${variable} or  __variable__ or ZZvariableZZ could be used instead?

SET @Cmd = 
     'CREATE TRIGGER $$SCHEMA_NAME$$.$$TRIGGER_NAME$$
      ON $$SCHEMA_NAME$$.$$VIEW_NAME$$ INSTEAD OF INSERT AS
      BEGIN
         RAISERROR(''Test system is in an invalid state. SetFakeViewOff must be called if SetFakeViewOn was called. Call SetFakeViewOff after creating all test case procedures.'', 16, 10) WITH NOWAIT;
         RETURN;
      END;
     ';

  SET @Cmd = REPLACE(@Cmd, '$$SCHEMA_NAME$$', QUOTENAME(@SchemaName));
  SET @Cmd = REPLACE(@Cmd, '$$VIEW_NAME$$', QUOTENAME(@ViewName));
  SET @Cmd = REPLACE(@Cmd, '$$TRIGGER_NAME$$', QUOTENAME(@TriggerName));

**Comment by mbt1** [comment]
I will look into this, but I might run into the new convention breaking some other framework.

**Comment by NReilingh** [comment]
I can't quite see why these token replacements are necessary at all. Couldn't this just be string concatenation?

**Comment by MattFloyd** [comment]
```
                var upgrader =
                    DeployChanges.To
                        .SqlDatabase(connectionString)
                        .WithVariable("SCHEMA_NAME", "$SCHEMA_NAME$")
                        .WithVariable("VIEW_NAME", "$VIEW_NAME$")
                        .WithVariable("TRIGGER_NAME", "$TRIGGER_NAME$")
                        .Build();
```

I'm not proud of this, but this will fix the problem.
