### ISSUE TITLE
FakeTable and a View

### ISSUE THREAD

**Issue by vkuharsky** [tSQLt-org/tSQLt#205]
Hello,
 I'm attempting to create a multi-table view for testing purposes, but I'm encountering an error: "Line 183: View or function 'View1' is not updatable because the modification affects multiple base tables." I receive this error when I attempt to execute an insert statement on the view. What's particularly puzzling is that when I include fewer columns in the initial insert statement, everything works as expected. Am I overlooking something, or is this behavior intentional?

**Comment by vkuharsky** [comment]
So, should I issue `exec tSQLt.FakeTable 'dbo.View1'` followed by an `exec sp_executesql ...` if I want to populate such view with testing data?

**Comment by dkultasev** [comment]
Yes

**Comment by vkuharsky** [comment]
Thanks. Your solution works great. 

It would be great if someone wrote a short explanation about this case on the `FakeTable` documentation page.

**Comment by dkultasev** [comment]
You are welcome. tSQLt is open source project, you can update documentation as well :)

**Comment by vkuharsky** [comment]
Okay, where I can get a source of `https://tsqlt.org/user-guide/isolating-dependencies/faketable/`?
