### ISSUE TITLE
ApplyConstraint for primary key not taking ignore_dup_key = on into account

### ISSUE THREAD

**Issue by pokorourk** [tSQLt-org/tSQLt#34]
It looks like ApplyConstraint is not incorporating ignore_dup_key = on into account. When I run ApplyConstraint with a primary key constraint with ignore_dup_key = on, and try to insert a record with a value that already exists, I get an exception when I don't expect one.

I believe this is happening because ApplyConstraint for unique constraints and primary key constraints are being handled the same. I can try to provide code to reproduce if it's not clear what is happening from the description here.

**Comment by lizbaron** [comment]
Hi @pokorourk,

Can you please say more about your use case and provide some sample code? Thank you!

--Liz

**Comment by pokorourk** [comment]
Unfortunately I don't have access to the project or use case I was working on when this issue was created. I'd say it can be closed.
