### ISSUE TITLE
tSQLt Installation instructions for SQL Azure

### ISSUE THREAD

**Issue by kgeorge314** [tSQLt-org/tSQLt#36]
Is it possible to update the QuickStart page https://tsqlt.org/user-guide/quick-start/ to mention that you do not need to enable CLR for sqlAzure databases, a few people were not aware that tSQLt works on Azure as they couldn't get past the first set of instructions. 

I suggest adding amending 

> 3. Make sure CLRs are enabled on your development server by running the following sql
```
EXEC sp_configure 'clr enabled', 1;
RECONFIGURE;
```
*TO* _something like_ 
> 3. Make sure CLRs are enabled on your development server by running the following sql (not required on SQL Azure Databases)

**Comment by abezverkov** [comment]
I would also like to know HOW its working ... we cant seem to load any OTHER CLR assemblies, but tSQLtCLR works just fine!

**Comment by mbt1** [comment]
It's whitelisted. One of the reasons why I haven't published a new version in a while, because there's no straightforward path to get the new version on the whitelist.

**Comment by mbt1** [comment]
Quickstart has been updated.

**Comment by TheConstructor** [comment]
> It's whitelisted. One of the reasons why I haven't published a new version in a while, because there's no straightforward path to get the new version on the whitelist.

But this should only apply to the assembly and updating the other parts should not be a problem, right?
