### ISSUE TITLE
tSQLt.ResultSetFilter  - error when procedure parametr is sql keyword

### ISSUE THREAD

**Issue by blepa** [tSQLt-org/tSQLt#4]
Hello,

I noticed that when the value of the parameter of tested procedure is equal to the sql keyword - procedure tSQLt.ResultSetFilter returns an error:

_System.Data.SqlClient.SqlException: Incorrect syntax near the keyword 'AS'._

Test script:

> USE tSQLt_Example
> GO
> 
> IF OBJECT_ID('dbo.uspForTest') IS NOT NULL
> 	DROP PROCEDURE dbo.uspForTest
> GO
> 
> CREATE PROCEDURE dbo.uspForTest
> (
> 	@InParam01 VARCHAR(20)
> )
> AS
> BEGIN
> 	SELECT @InParam01 [InParam01]
> ENd
> GO
> 
> IF OBJECT_ID('dbo.test_uspForTest') IS NOT NULL
> 	DROP PROCEDURE dbo.test_uspForTest
> GO
> 
> -- ok test case
> CREATE PROCEDURE dbo.test_uspForTest
> AS 
> BEGIN
> 
> 	CREATE TABLE #uspForTest
> 	(
> 		InParam01 VARCHAR(20)
> 	)
> 
> 	DECLARE @Command VARCHAR(4000)
> 	DECLARE @InParam01 VARCHAR(20) 
> 
> 	SET @InParam01 = 'AT'
> 
> 	SET @Command = 'EXEC dbo.uspForTest @InParam01 = ' + @InParam01
> 
> 	INSERT INTO #uspForTest
> 	EXEC tSQLt.ResultSetFilter 
> 			@ResultsetNo = 1
> 		,	@Command = @Command	
> 		
> 
> 	SELECT * FROM #uspForTest
> END
> GO
> 
> EXEC tSQLt.Run '[dbo].[test_uspForTest]'
> GO
> 
> -- error test case
> ALTER PROCEDURE dbo.test_uspForTest
> AS 
> BEGIN
> 
> 	CREATE TABLE #uspForTest
> 	(
> 		InParam01 VARCHAR(20)
> 	)
> 
> 	DECLARE @Command VARCHAR(4000)
> 	DECLARE @InParam01 VARCHAR(20) 
> 
> 	SET @InParam01 = 'AS'
> 
> 	SET @Command = 'EXEC dbo.uspForTest @InParam01 = ' + @InParam01
> 
> 	INSERT INTO #uspForTest
> 	EXEC tSQLt.ResultSetFilter 
> 			@ResultsetNo = 1
> 		,	@Command = @Command	
> 		
> 
> 	SELECT * FROM #uspForTest
> END
> GO
> 
> EXEC tSQLt.Run '[dbo].[test_uspForTest]'
> GO
> 
> 
>

**Comment by blepa** [comment]
Solution:

SET @InParam01 = '''AS'''

Issue for close!.

**Comment by mbt1** [comment]
This is not a ResultSetFilter issue. But it looks like you figured that out already.
