### ISSUE TITLE
"Tables without a primary key" confuses a Database Role for a table

### ISSUE THREAD

**Issue by pinnacleapi** [tSQLt-org/tSQLt#44]
In a fresh installation of SQL Test I added one of my database and notice the built-in test case "Tables without a primary key" fails and in the output where I would expect to see the list of table(s) breaching the rule I see database roles. The output looks like this: 

> 
Test Procedure: [dbname].[SQLCop].[test Tables without a primary key] on servername 
[SQLCop].[test Tables without a primary key] failed: (Failure) 

myRoleHere.Private_AssertEqualsTableSchema_Actual 
myRoleHere.Private_AssertEqualsTableSchema_Expected 
myRoleHere.Private_ExpectException 
myRoleHere.Private_NullCellTable 
myRoleHere.Run_LastExecution 
myRoleHere.TestMessage
> 

Please note that there is no tables or any other objects in my database with the same name as my role. 

The issue was reported to RedGate and their development team confirmed the issue lies in the tSQLt framework so they can't fix it.

I fixed the issue locally by updating the built-in sproc : 
       [SQLCop].[test Tables without a primary key]

to include this WHERE condition: 
       AND ISNULL(u.issqlrole, 0) = 0

-----------------

Please note another test, "Procedures that call undocumented procedures" , fails with a similar problem where it confuses a role for a sproc... I fixed that one locally the same way, by tweaking filtering our sqlroles in the where clause in [SQLCop].[test Procedures that call undocumented procedures]

-----------------

**Comment by harveysburger** [comment]
apologies, the issue lies in SQLCop , we reported the issue there instead, closing this one...

**Comment by pinnacleapi** [comment]
apologies, the issue lies in SQLCop…
