### ISSUE TITLE
Bug in AssertEmptyTable - cross-database/3-part @TableName not handled correctly

### ISSUE THREAD

**Issue by Jevonius** [tSQLt-org/tSQLt#60]
Hi,

We have just noticed a bug with `AssertEmptyTable`, specifically when checking a table in another database. If you pass in `[AnotherDatabase].dbo.MyTable`, `OBJECT_ID` returns a value (assuming the table _does_ exist!), so the code flows to:
```  SET @FullName = tSQLt.Private_GetQuotedFullName(OBJECT_ID(@TableName));```

Unfortunately `Private_GetQuotedFullName` doesn't know you're providing an OBJECT_ID that is in a different database, so you get a different FullName back than expected (in our case `tSQLt.LogCapturedOutput` among others) which means the execution fails further down (it ended up trying to do a `SELECT 1 FROM <stored procedure>` which errored).

I'm not sure what the correct fix should be - potentially `PARSENAME` could be used to see if a database name is provided, and this could be checked against `DB_NAME()`, but I don't know how far back that is supported, and/or if `Private_GetQuotedFullName` would also need to be expanded to support a database name (or if that should just happen in `AssertEmptyTable`?).

**Comment by mbt1** [comment]
None of the tSQLt functionality at this time supports cross-database testing. That functionality is on the backlog but I can't give a timeline at this point.

**Comment by Jevonius** [comment]
Missed that! Some does work by chance though - further down the test we use `AssertEqualsTable` and pass a 3-part name as the Actual parameter and it appears to work.

Thanks for the quick response, will have a think how we can do this an alternative way (with Views perhaps).

**Comment by mbt1** [comment]
In general, you don't want to use 3-part names in your database code. Instead, use auto-generated pass-through modules (views, 1-line SSPs, synonyms, and so on). That makes your code way more flexible and easier to test.
