### ISSUE TITLE
Annotation Skip is SkipTest 

### ISSUE THREAD

**Issue by mennodekker** [tSQLt-org/tSQLt#76]
I tried the new version today and found out that to skip a test I need to use --[@tSQLt:SkipTest]('Some reason') to get it working. In the releasenotes it tells the annotation is --[@tSQLt:Skip]('Some reason') (so no Test after Skip)

It would be nice if this was updated in releasenotes and an example in the documentation would be greatly appreciated. Keep up the good work :)

**Comment by PratikshaPaudyalAwaze** [comment]
Hi @mennodekker 
I'm trying to run the skip test annotation but it's not currently working 

EXEC tSQLt.[@tSQLt:SkipTest] 'Reason'
CREATE PROCEDURE testModule01.[test that asserts ....]

AS
BEGIN

    DECLARE @Actual INT;
    DECLARE @Message VARCHAR(350)
    SELECT @Actual= ....;
    DECLARE @Expected INT; SET @Expected = year(GetDate())-1;
    EXEC tSQLt.AssertEquals @Expected, @Actual, @Message;

END;
go


But this is currently not working due to syntax errors. 
How did you get it to work?

**Comment by mennodekker** [comment]
You should do it in comments like this:
```
--[@tSQLt:SkipTest]('Temporarily disabled while refactoring')
CREATE PROCEDURE testModule01.[test that asserts ....]

AS
BEGIN
```

**Comment by PratikshaPaudyalAwaze** [comment]
@mennodekker Thank you!!!

**Comment by mbt1** [comment]
This was fixed. Thank you for reporting.
