### ISSUE TITLE
Copyright or -left License 

### ISSUE THREAD

**Issue by JohnKNess** [tSQLt-org/tSQLt#8]
I noticed that your work does not contain a license file and was just wondering if you have any ideas about the license you would like to issue with your intellectual property? According to the [Choose an open source](http://choosealicense.com/no-license/) website your property already contains an explicit license:

> Opting out of open source licenses doesn’t mean you’re opting out of copyright law.
> 
> You’ll have to check with your own legal counsel regarding your particular project, but generally  speaking, the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.
> 
> You don’t have to do anything to not offer a license, though including a copyright notice is recommended. [...]

Currently this basically means that I don't have permissions to re-use your code without your consent (sort of), which somehow collides with the idea of GitHub being pretty much open.

**Comment by JohnKNess** [comment]
... According to the [Choose an open source license](http://choosealicense.com/) website ...

**Comment by mbt1** [comment]
tSQLt is Licensed under Apache 2.0 ([License.txt](https://github.com/tSQLt-org/tSQLt/blob/master/Build/License.txt)
