### ISSUE TITLE
mock data table

### ISSUE THREAD

**Issue by lastlink** [tSQLt-org/tSQLt#83]
to make our mock data more maintainable we started using csv's that were serialized using powershell and inserted into a mock table as part of a base tsqlt visual studio sql server project.

tSQLT.MockData
```sql
CREATE TABLE tSQLT.MockData
(
[Id] INT NOT NULL Primary Key Identity,
[Description] varchar(255) NOT NULL,
[RawData] TEXT NOT NULL -- json array
)

CREATE UNIQUE INDEX [IX_MockData_Description_Unique] ON tSQLT.MockData ([Description])
```

PublishMockData.ps1
```ps1
Param(
    [Parameter(Mandatory = $true)]
    [string]$server,
    [Parameter(Mandatory = $true)]
    [string]$rootFolder,
    [Parameter(Mandatory = $true)]
    [string]$database
)

$folders = Get-ChildItem $rootFolder -Recurse | ? { $_.PSIsContainer }

$query = ""
foreach ($fodler in $folders) {
    $parentFolder = $folder.Name
    $files = Get-ChildItem $folder.FullName -Recurse *.csv

    foreach ($f in $files) {
        $jsonData = import-csv $f.FullName | ConvertTo-Json
        # make json an array if only one entry
        if($jsonData[0] -ne "["){
            $jsonData = "[" + $jsonData + "]"
        }

        $desc = $f.Name.Replace($f.Extension, "")
        # remove new lines
        $jsonData = $jsonData.Replace("`n", "")

        $query += "`n INSERT INTO [tSQLT].[MockData] ([Description], [RawData])"
        $query += "`n VALUES ('$parentFolder-$desc','$jsonData');"

        Write-Host "Desc:$parentFolder-$desc" -foregroundcolor white
    }
}

Out-File -FilePath \mockDataInsert.sql -InputObject $query

$fullSyntax = "sqlcmd -S $server -d $database -i "".\mockDataInsert.sql"" "

cmd /c $fullSyntax
```

## steps
* deploy db
* read csv files and insert into this table as JSONArrays for each
* when running unit tests, .SETUP proc calls a base POPULATE proc that fakes tables, loads data from tSQLT.MockData as reading json then select insert into tables

## additional notes
* I've also started putting expected results into the table as well
* experimented w/ serializing whole table to json and comparing against data entry, also trying out red gate sql json diff for better comparison in test results https://www.red-gate.com/simple-talk/blogs/sql-server-json-diff-checking-for-differences-between-json-documents/
* using csv files instead of manual inserts has been much easier to maintain, now we just add new rows, and change selects and columns rather than new manual insert lines

**Comment by mbt1** [comment]
This is not an issue. However, please consider starting a conversation on the tSQLt Google Group (https://groups.google.com/g/tsqlt) or the tSQLt channel in the SQL Server Community on Slack (http://aka.ms/sqlslack).
