### ISSUE TITLE
tSQLt.ExpectException should print the expected error message when it fails

### ISSUE THREAD

**Issue by lizbaron** [tSQLt-org/tSQLt#86]
It would be nice if the tSQLt.ExpectException could print the expected error message when it fails, so that we don't have to look it up.

**Comment by mbt1** [comment]
The expected message is printed only if it does not match, not in the case of other mismatches, like Severity or State. It is unclear how adding the expected error message in these cases would help with understanding. The test name should provide enough information in these cases.

**Comment by MatheusCylo** [comment]
If the purpose is ensuring the correct exception message is emitted in the context of, for instance, a test suite to avoid regressions during refactoring, there's a trick I commonly use: I start by asserting that the exception message will be something silly, such as `'asdf'`, then run the test. The test will obviously fail, and the assertion error will contain the actually emitted exception message. I then copy+paste that message into my test assertion.
